### ISSUE TITLE
Why is self-adversarial negative sampling unfair?

### ISSUE THREAD

**Issue by apoorvumang** [ibalazevic/TuckER#13]
You have said that 'The RotatE (Sun et al., 2019) results are reported without their self-adversarial negative sampling (see Appendix H in the original paper) for fair comparison'

What is the reason for it being unfair?

**Comment by ibalazevic** [comment]
Self-adversarial negative sampling in itself is a perfectly valid thing to do. However, given that it is not specific to RotatE only, it can be used with other models. Since the authors of the RotatE paper show that it increases performance and given that no other models whose results we report use it (including TuckER), we report the RotatE results without it for fair comparison.
